// src/app/layout.tsx
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Toaster } from "@/components/ui/toaster";
import { FirebaseClientProvider } from "@/firebase/client-provider";
import { AuthProvider } from "@/context/AuthContext";
import { RolesProvider } from "@/context/RolesContext";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "ManpowerFlow",
  description: "Generated by Firebase Studio",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={inter.className}>
        <FirebaseClientProvider>
            <AuthProvider>
                <RolesProvider>
                    {children}
                    <Toaster />
                </RolesProvider>
            </AuthProvider>
        </FirebaseClientProvider>
      </body>
    </html>
  );
}
