// src/app/layout.tsx
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { FirebaseClientProvider } from "@/firebase/client-provider";
import { RolesProvider } from "@/context/RolesContext";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Canonical Starter App",
  description: "Generated by Firebase Studio",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <FirebaseClientProvider>
          <RolesProvider>{children}</RolesProvider>
        </FirebaseClientProvider>
      </body>
    </html>
  );
}
